INSERT INTO [Countries] (Name) VALUES ('ARGENTINA');
INSERT INTO [States] (Name, CountryId) VALUES ('TUCUMÁN', 1);
INSERT INTO [States] (Name, CountryId) VALUES ('BUENOS AIRES', 1);
INSERT INTO [Cities] (Name, StateId) VALUES ('San Miguel de Tucumán', 1);
INSERT INTO [PostalCodes] (Code, CityId) VALUES ('T4000ABQ', 1);
INSERT INTO [PostalCodes] (Code, CityId) VALUES ('T4000CVJ', 1);
INSERT INTO [PostalCodes] (Code, CityId) VALUES ('T4000ABR', 1);
INSERT INTO [Streets] (Name, Number) VALUES ('Av. Gral. Roca', 490);
INSERT INTO [Streets] (Name, Number) VALUES ('Gral. José de San Martín', 586);
INSERT INTO [Streets] (Name, Number) VALUES ('Av. Gral. Roca', 587596); 
INSERT INTO [Addresses] (StreetId, PostalCodeId) VALUES (1, 1);
INSERT INTO [Addresses] (StreetId, PostalCodeId) VALUES (2, 2);
INSERT INTO [Addresses] (StreetId, PostalCodeId) VALUES (3, 3);
INSERT INTO [GeoCoordinates] (Latitude, Longitude) VALUES (-26.8298721, -65.2039887);
INSERT INTO [GeoCoordinates] (Latitude, Longitude) VALUES (-26.8439117, -65.2083509);
INSERT INTO [GeoCoordinates] (Latitude, Longitude) VALUES (-26.8422439, -65.2159435);
INSERT INTO [Customers] (IdentificationNumber, Name) VALUES ('13-12332333-4', 'Shell Francisco Jaime Mena SRL');
INSERT INTO [Customers] (IdentificationNumber, Name) VALUES ('20-24987665-9', 'Banco Santander Río');
INSERT INTO [Customers] (IdentificationNumber, Name) VALUES ('20-25987665-0', 'Supermercado VEA SRL');
INSERT INTO [EnergySupplyGroups] (Name, Description) VALUES ('METRO-OESTE', 'Grupo de Suministros de Zona Metropolitana Oeste');
INSERT INTO [EnergySupplies] (Code, AddressId, CustomerId, GeoCoordinateId, GroupId) VALUES ('ES-332123-TUC', 1, 1, 1, 1);
INSERT INTO [EnergySupplies] (Code, AddressId, CustomerId, GeoCoordinateId, GroupId) VALUES ('ES-988764-TUC', 2, 2, 2, 1);
INSERT INTO [EnergySupplies] (Code, AddressId, CustomerId, GeoCoordinateId, GroupId) VALUES ('ES-877656-TUC', 3, 3, 3, 1);
INSERT INTO [MeterManufacturers] (Name) VALUES ('Elster Group');
INSERT INTO [PhoneCompanies] (Name) VALUES ('Personal Argentina SRL'); 
INSERT INTO [SIMCardServices] (Name, Description) VALUES ('Middelware', 'Servicio de telefonía para Telemedición modalidad Middleware');
INSERT INTO [SIMCardServices] (Name, Description) VALUES ('Jasper VPN', 'Servicio de telefonía para Telemedición modalidad Jasper (VPN)');
INSERT INTO [SIMCards] (SerialNumber, PhoneNumber, PhoneCompanyId, ServiceId) VALUES ('ARG381-44323331', '+54 381 5664323', 1, 2);
INSERT INTO [SIMCards] (SerialNumber, PhoneNumber, PhoneCompanyId, ServiceId) VALUES ('ARG381-65433212', '+54 381 4765542', 1, 1);
INSERT INTO [Vendors] (Name, Description) VALUES ('GENROD SRL', 'Empresa Argentina que fabrica y comercializa soluciones eléctricas y tecnológicas');
INSERT INTO [RemoteDevices] (Model, SerialNumber, Ip, PortNumber, SIMCardId, VendorId) VALUES ('TEA-S001', 'SN8573723429', '172.31.0.9', 2503, 1, 1);
INSERT INTO [RemoteDevices] (Model, SerialNumber, Ip, PortNumber, SIMCardId, VendorId) VALUES ('TEA-S002', 'SN8573723430', '172.31.0.10', 2503, 2, 1);
INSERT INTO [Meters] (Model, SerialNumber, EnergySupplyId, MeterManufacturerId, RemoteDeviceId) VALUES ('A3R-lqs RS232/485', 4021100, 1, 1, 1);
INSERT INTO [Meters] (Model, SerialNumber, EnergySupplyId, MeterManufacturerId) VALUES ('A3R-lqs Nodo-C', 4021079, 2, 1);
INSERT INTO [Meters] (Model, SerialNumber, EnergySupplyId, MeterManufacturerId, RemoteDeviceId) VALUES ('A3R-lqs RS232/485', 4041723, 3, 1, 2);
INSERT INTO [MeterSessionTypes] (Name, Description) VALUES ('Insitu', 'Sesión de Comunicación modalidad Insitu');
INSERT INTO [MeterSessionTypes] (Name, Description) VALUES ('Remote', 'Sesión de Comunicación modalidad Remota');
INSERT INTO [MeterProtocolSettings] (UserId, UserName, Password)	VALUES (2, 'Administrator', 'jrrb&240366');
INSERT INTO [MeterProtocolSettings] (UserId, UserName, Password)	VALUES (2, 'Administrator', 'alpha3superioruser');
INSERT INTO [CommunicationChannelSettings] (SendAckResponseThershold, BaudRate, PacketSize, NumberOfPackets, ChannelTrafficTimeout, InterCharacterTimeout, ResponseTimeout, NumberOfRetries) VALUES (100, 6, 1024, 1, 255, 1, 255, 3);
INSERT INTO [MeterSessionReconnectionSchemas] (MaxReconnectionAttempts) VALUES (2);
INSERT INTO [ReconnectionSchedules] (Schedule, MeterSessionReconnectionSchemaId) VALUES (60, 1);
INSERT INTO [ReconnectionSchedules] (Schedule, MeterSessionReconnectionSchemaId) VALUES (120, 1);
INSERT INTO [MeterSessionSettings] (Name, InternalReconnectionAttempts, ProtocolSettingId, ReconnectionSchemaId, CommunicationChannelSettingId) VALUES ('Default|Remote', 1, 1, 1, 1);
INSERT INTO [MeterSessionSettings] (Name, InternalReconnectionAttempts, ProtocolSettingId) VALUES ('Default|Insitu', 1, 2);
INSERT INTO [RemoteMeterSessionSettings] (UseMeterMAXProtocol, MeterSessionSettingId) VALUES (1, 1);
INSERT INTO [InsituMeterSessionSettings] (PortName, DtrEnabled, MeterSessionSettingId) VALUES ("COM1:", 0, 2);
INSERT INTO [DataSets] (Name, Description) VALUES ('FACTURACIÓN', 'Cronograma de Tareas para recolectar datos de Facturación, estado del Medidor y datos Instrumentales');
INSERT INTO [DataSets] (Name, Description) VALUES ('ESTADO DE SALUD', 'Cronograma de Tareas para recolectar datos con el objetivo de comprobar el estado de salud y eventos del Medidor.');
INSERT INTO [DataSets] (Name, Description) VALUES ('PERFIL DE CARGA', 'Cronograma de Tareas para recolectar datos del Perfil de Carga del Medidor');
INSERT INTO [DataSetComponents] (Name, Description) VALUES ('Firmware e Identificación', 'Recolectar información de versión de Firmware e Identificación del Medidor.');
INSERT INTO [DataSetComponents] (Name, Description) VALUES ('Configuración Computacional', 'Recolectar información relacionada a la configuración computacional y multiplicadores.');
INSERT INTO [DataSetComponents] (Name, Description) VALUES ('Facturación Mes Actual', 'Recolectar información de facturación relacionada al Mes Vigente.');
INSERT INTO [DataSetComponents] (Name, Description) VALUES ('Facturación Mes Previo', 'Recolectar información de facturación relacionada al Mes Previo (luego de reseteo de demanda).');
INSERT INTO [DataSetComponents] (Name, Description) VALUES ('Estado de Salud', 'Recolectar información relacionada a la Salud del Medidor y eventos de seguridad registrados.');
INSERT INTO [DataSetComponents] (Name, Description) VALUES ('Datos de Instrumentación', 'Recolectar información de instrumentación, valores instantáneos de tensión y corriente.');
INSERT INTO [DataSetComponents] (Name, Description) VALUES ('Perfil de Carga', 'Recolectar información del perfil de carga para visualizar la curva de consumo en el tiempo.');
INSERT INTO [DataSets_DataSetComponents] (DataSetId, DataSetComponentId) VALUES (1, 1);
INSERT INTO [DataSets_DataSetComponents] (DataSetId, DataSetComponentId) VALUES (1, 2);
INSERT INTO [DataSets_DataSetComponents] (DataSetId, DataSetComponentId) VALUES (1, 3);
INSERT INTO [DataSets_DataSetComponents] (DataSetId, DataSetComponentId) VALUES (1, 4);
INSERT INTO [DataSets_DataSetComponents] (DataSetId, DataSetComponentId) VALUES (1, 5);
INSERT INTO [DataSets_DataSetComponents] (DataSetId, DataSetComponentId) VALUES (1, 6);
INSERT INTO [DataSets_DataSetComponents] (DataSetId, DataSetComponentId) VALUES (2, 1);
INSERT INTO [DataSets_DataSetComponents] (DataSetId, DataSetComponentId) VALUES (2, 5);
INSERT INTO [DataSets_DataSetComponents] (DataSetId, DataSetComponentId) VALUES (3, 1);
INSERT INTO [DataSets_DataSetComponents] (DataSetId, DataSetComponentId) VALUES (3, 7);
